version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/DockerFile
    command: sleep infinity
    volumes:
      - ../:/app
    environment:
      - NODE_ENV=development